In [1]:
import numpy as np
import pandas as pd

In [2]:
# Dataframe:

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25], 
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 700000, 62000, np.nan, 50000]
}

In [3]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 700000, 62000, nan, 50000]}

In [6]:
df = pd.DataFrame(data)
df

      Name   Age Department    Salary
0    Alice  25.0         HR   50000.0
1      Bob  30.0         IT   60000.0
2  Charlie  35.0    Finance  700000.0
3    David   NaN         IT   62000.0
4      Eve  29.0         HR       NaN
5    Alice  25.0         HR   50000.0

In [8]:
df.head(2) # By default the paramter inside the head and tail is 5

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

In [9]:
df.tail(2)

    Name   Age Department   Salary
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [7]:
# loc and iloc

df.iloc[1:3, :2] # Rows,Column

      Name   Age
1      Bob  30.0
2  Charlie  35.0

In [8]:
df.loc[1:2, ["Age", "Salary"]] # Rows, and column are named not index

    Age    Salary
1  30.0   60000.0
2  35.0  700000.0

In [9]:
df[["Age", "Name"]]

    Age     Name
0  25.0    Alice
1  30.0      Bob
2  35.0  Charlie
3   NaN    David
4  29.0      Eve
5  25.0    Alice

In [12]:
df.drop("Age", axis = 1)
# df.drop("Age", axis = 1, inplace= True) here inplace is used to change the original dataframe

      Name Department    Salary
0    Alice         HR   50000.0
1      Bob         IT   60000.0
2  Charlie    Finance  700000.0
3    David         IT   62000.0
4      Eve         HR       NaN
5    Alice         HR   50000.0

In [11]:
df

      Name   Age Department    Salary
0    Alice  25.0         HR   50000.0
1      Bob  30.0         IT   60000.0
2  Charlie  35.0    Finance  700000.0
3    David   NaN         IT   62000.0
4      Eve  29.0         HR       NaN
5    Alice  25.0         HR   50000.0

In [12]:
df.shape

(6, 4)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [14]:
df.describe()

             Age         Salary
count   5.000000       5.000000
mean   28.800000  184400.000000
std     4.147288  288282.500336
min    25.000000   50000.000000
25%    25.000000   50000.000000
50%    29.000000   60000.000000
75%    30.000000   62000.000000
max    35.000000  700000.000000

In [15]:
mod = df.median(numeric_only=True)

df.fillna(mod)

      Name   Age Department    Salary
0    Alice  25.0         HR   50000.0
1      Bob  30.0         IT   60000.0
2  Charlie  35.0    Finance  700000.0
3    David  29.0         IT   62000.0
4      Eve  29.0         HR   60000.0
5    Alice  25.0         HR   50000.0

In [16]:
# Broadcasting 

df["Salary"] = df["Salary"] + 500
df["Salary"]

0     50500.0
1     60500.0
2    700500.0
3     62500.0
4         NaN
5     50500.0
Name: Salary, dtype: float64

In [43]:
# Renaming columns:

df.rename(columns = {"Department": "Dept"}, inplace= True)

C:\Users\Aashish\AppData\Local\Temp\ipykernel_22760\908063925.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {"Department": "Dept"}, inplace= True)

In [44]:
df

    Name   Age     Dept    Salary  Promoted Salary
0  Alice  25.0       HR   50000.0         500000.0
1    Bob  30.0       IT   60000.0         600000.0
2   Rose  35.0  Finance  700000.0         700000.0
3  David  29.0       IT   62000.0         620000.0
4    Eve  29.0       HR       NaN              NaN

In [19]:
df["Salary"].unique()

array([ 50500.,  60500., 700500.,  62500.,     nan])

In [20]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [21]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [19]:
df["Promoted Salary"] = df["Salary"] * 10

In [20]:
df

      Name   Age Department    Salary  Promoted Salary
0    Alice  25.0         HR   50000.0         500000.0
1      Bob  30.0         IT   60000.0         600000.0
2  Charlie  35.0    Finance  700000.0        7000000.0
3    David   NaN         IT   62000.0         620000.0
4      Eve  29.0         HR       NaN              NaN
5    Alice  25.0         HR   50000.0         500000.0

In [21]:
# Data cleaning

df.isnull().sum()

Name               0
Age                1
Department         0
Salary             1
Promoted Salary    1
dtype: int64

In [22]:
df.dropna()

      Name   Age Department    Salary  Promoted Salary
0    Alice  25.0         HR   50000.0         500000.0
1      Bob  30.0         IT   60000.0         600000.0
2  Charlie  35.0    Finance  700000.0        7000000.0
5    Alice  25.0         HR   50000.0         500000.0

In [23]:
df.dropna(how = "any") # Any row that have any null value

      Name   Age Department    Salary  Promoted Salary
0    Alice  25.0         HR   50000.0         500000.0
1      Bob  30.0         IT   60000.0         600000.0
2  Charlie  35.0    Finance  700000.0        7000000.0
5    Alice  25.0         HR   50000.0         500000.0

In [24]:
df.dropna(how = "all") # If alll the value in that row is null then drop it otherwise do nothing

      Name   Age Department    Salary  Promoted Salary
0    Alice  25.0         HR   50000.0         500000.0
1      Bob  30.0         IT   60000.0         600000.0
2  Charlie  35.0    Finance  700000.0        7000000.0
3    David   NaN         IT   62000.0         620000.0
4      Eve  29.0         HR       NaN              NaN
5    Alice  25.0         HR   50000.0         500000.0

In [25]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [26]:
df["Salary"].fillna(df["Salary"].median())

0     50000.0
1     60000.0
2    700000.0
3     62000.0
4     60000.0
5     50000.0
Name: Salary, dtype: float64

In [27]:
df["Age"].fillna(method = "ffill")

C:\Users\Aashish\AppData\Local\Temp\ipykernel_22760\1282635122.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill")

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [28]:
df["Age"].fillna(method = "bfill")

C:\Users\Aashish\AppData\Local\Temp\ipykernel_22760\3026805218.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill")

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [29]:
df["Age"] = df["Age"].bfill()

In [30]:
df

      Name   Age Department    Salary  Promoted Salary
0    Alice  25.0         HR   50000.0         500000.0
1      Bob  30.0         IT   60000.0         600000.0
2  Charlie  35.0    Finance  700000.0        7000000.0
3    David  29.0         IT   62000.0         620000.0
4      Eve  29.0         HR       NaN              NaN
5    Alice  25.0         HR   50000.0         500000.0

In [31]:
df["Name"] = df["Name"].replace("Charlie", "Rose")

In [32]:
df

    Name   Age Department    Salary  Promoted Salary
0  Alice  25.0         HR   50000.0         500000.0
1    Bob  30.0         IT   60000.0         600000.0
2   Rose  35.0    Finance  700000.0        7000000.0
3  David  29.0         IT   62000.0         620000.0
4    Eve  29.0         HR       NaN              NaN
5  Alice  25.0         HR   50000.0         500000.0

In [33]:
df_dup = df[df.duplicated(keep= "first")]
df_dup

    Name   Age Department   Salary  Promoted Salary
5  Alice  25.0         HR  50000.0         500000.0

In [34]:
df_dup = df[df.duplicated(keep= "last")] # This will priorities last data and rather than last data if any duplicate is available this command will show that.
df_dup

    Name   Age Department   Salary  Promoted Salary
0  Alice  25.0         HR  50000.0         500000.0

In [35]:
df = df.drop_duplicates()

In [36]:
df

    Name   Age Department    Salary  Promoted Salary
0  Alice  25.0         HR   50000.0         500000.0
1    Bob  30.0         IT   60000.0         600000.0
2   Rose  35.0    Finance  700000.0        7000000.0
3  David  29.0         IT   62000.0         620000.0
4    Eve  29.0         HR       NaN              NaN

In [37]:
# Invalid values:
# Lambda -> python

df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x > 650000 else x)

C:\Users\Aashish\AppData\Local\Temp\ipykernel_22760\1901105956.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x > 650000 else x)

In [38]:
df

    Name   Age Department    Salary  Promoted Salary
0  Alice  25.0         HR   50000.0         500000.0
1    Bob  30.0         IT   60000.0         600000.0
2   Rose  35.0    Finance  700000.0         700000.0
3  David  29.0         IT   62000.0         620000.0
4    Eve  29.0         HR       NaN              NaN

In [ ]:
# The command given below is used to split the string any column or row but it is used when i have a string available in the dataframe that is divided by some characters like("_", " ", etc.)


# name = "alice_fernandes"
# df[["first_name", "last_name"]] = df["name"].str.split("_")

In [43]:
# Apply and lambda:
def multiplying_age(x):
    return x*2

df["Age"] = df["Age"].apply(multiplying_age)

C:\Users\Aashish\AppData\Local\Temp\ipykernel_9552\3706214153.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(multiplying_age)

In [44]:
df

    Name   Age     Dept    Salary  Promoted Salary
0  Alice  50.0       HR   50500.0         505000.0
1    Bob  60.0       IT   60500.0         605000.0
2   Rose  70.0  Finance  700500.0         700500.0
3  David  58.0       IT   62500.0         625000.0
4    Eve  58.0       HR       NaN              NaN

In [45]:
df["Age"] = df["Age"].apply(lambda x:x/2)

C:\Users\Aashish\AppData\Local\Temp\ipykernel_9552\545583777.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(lambda x:x/2)

In [46]:
df

    Name   Age     Dept    Salary  Promoted Salary
0  Alice  25.0       HR   50500.0         505000.0
1    Bob  30.0       IT   60500.0         605000.0
2   Rose  35.0  Finance  700500.0         700500.0
3  David  29.0       IT   62500.0         625000.0
4    Eve  29.0       HR       NaN              NaN

In [39]:
# Joins and merges

department_info = {
    "Dept": ["HR", "IT", "Finance"], 
    "Locatoin": ["New York", "San francisco", "Chicago"],
    "Manager": ["Laura", "Steve", "Nina"]
}

df2 = pd.DataFrame(department_info)
df2

      Dept       Locatoin Manager
0       HR       New York   Laura
1       IT  San francisco   Steve
2  Finance        Chicago    Nina

In [40]:
# Concat

pd.concat([df, df2])

,Name,Age,Department,Salary,Promoted Salary,Dept,Locatoin,Manager
0,Alice,25.0,HR,50000.0,500000.0,NaN,NaN,NaN
1,Bob,30.0,IT,60000.0,600000.0,NaN,NaN,NaN
2,Rose,35.0,Finance,700000.0,700000.0,NaN,NaN,NaN
3,David,29.0,IT,62000.0,620000.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,HR,New York,Laura
1,NaN,NaN,NaN,NaN,NaN,IT,San francisco,Steve
2,NaN,NaN,NaN,NaN,NaN,Finance,Chicago,Nina

In [41]:
pd.concat([df, df2], axis=1)

,Name,Age,Department,Salary,Promoted Salary,Dept,Locatoin,Manager
0,Alice,25.0,HR,50000.0,500000.0,HR,New York,Laura
1,Bob,30.0,IT,60000.0,600000.0,IT,San francisco,Steve
2,Rose,35.0,Finance,700000.0,700000.0,Finance,Chicago,Nina
3,David,29.0,IT,62000.0,620000.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN

In [45]:
pd.merge(df, df2, on = "Dept")

    Name   Age     Dept    Salary  Promoted Salary       Locatoin Manager
0  Alice  25.0       HR   50000.0         500000.0       New York   Laura
1    Bob  30.0       IT   60000.0         600000.0  San francisco   Steve
2   Rose  35.0  Finance  700000.0         700000.0        Chicago    Nina
3  David  29.0       IT   62000.0         620000.0  San francisco   Steve
4    Eve  29.0       HR       NaN              NaN       New York   Laura

### Importing File

In [ ]:
from pathlib import Path

In [52]:
file_path = Path(r"C:\Users\Aashish\OneDrive\Desktop\New Microsoft Excel Worksheet.xlsx")
data = pd.read_excel(file_path)

In [ ]:
print(data.head())

Empty DataFrame
Columns: []
Index: []

In [57]:
data.shape

(0, 0)

In [ ]:
# data["date"] = pd.to_datetime(data["date"]) This will change the data type of the column